FROM python:3.11-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1

COPY requirements-python.txt ./

RUN pip install --no-cache-dir -r requirements-python.txt

COPY . .

EXPOSE 5001

CMD ["python3", "1.py"]
